# Include variables and stages
# from noah-pipelines-templates project 
include:
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'variables.yml'
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'terraform_tmpl.yml'

# Stage availables for this pipeline
stages:
  - run-security-scan 
  - infrastructure
  - test_documentation
  - deploy_documentation

# Runs tfsec module scan from noah-pipelines-templates project
run-security-scan:
  stage: run-security-scan
  extends: .module_security_scan
  variables:
    PATH_TO_SCAN: "environments/test/"
  script: 
    - echo "Starting Terraform module security scan"

# Run terraform template job from noah-pipelines-templates project
infrastructure:
  stage: infrastructure
  extends: .terraform
  variables:
    AWS_PROFILE_ENV: $TF_USER_DURABLE_DEV_ENV
  script:
    - echo "Running durable resource pipeline"
    - cd environments/dev/
    - pwd
    - terraform init
    - terraform plan -var-file=dev.tfvars
    - terraform apply -var-file=dev.tfvars -auto-approve 

# Test the build for the Terraform documentation
test:
  stage: test_documentation
  extends: .test_mkdocs_build
  script:
    - echo "Generated Terraform documentations artifact"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH


# Deploy the Terraform Documentation to GitLab pages
pages:
  stage: deploy_documentation
  extends: .deploy_pages
  script:
    - echo "Publishing Terraform documentations"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
