site_name: AWS Durable Resources Terraform Documentation
site_url: "https://gitlab.com/noah-energy/infranoah/durable-resources-aws"
repo_url: https://gitlab.com/noah-energy/infranoah/durable-resources-aws
site_dir: public
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  features:
      - navigation.expand
nav:
    - index.md
    - 'Environments':
        - dev: 'dev.md'
        - prod: 'prod.md'
    - 'modules':
        - s3: 
            - bucketDjango: 'djangoBuckets.md'
        - createIamGroups:
            - groupEKS: 'createGroups.md'
        - usersAccountIAM:
            - developmentUsers: 'developmentUsers.md'
            - terraformUsers: 'terraformUsers.md'
        - Roles:
            - workerNode: 'eksWorkerNodeRole.md'
            - clusterEKS: 'eksClusterRole.md'